/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProyectoSprint3;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author amore INICIAMOS COMPONENTES PRINCIPALES DE LA INTERFAZ CREAR
 * CATEGORÍA
 *
 */
public final class GUICrearCategoria extends javax.swing.JFrame {

    public GUICrearCategoria() {
        initComponents();
        funcionCerrar();

        //Funciones gráficas varias
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getClassLoader().getResource("imagenes/icon.jpg")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        labelCrearCategoria = new javax.swing.JLabel();
        imgEmpresa = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        labelContenido = new javax.swing.JLabel();
        labelMetadescription = new javax.swing.JLabel();
        labelSitemap = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        textTitulo = new javax.swing.JTextField();
        scrollContenido = new javax.swing.JScrollPane();
        textContenido = new javax.swing.JTextArea();
        scrollMetadesc = new javax.swing.JScrollPane();
        textMetadesc = new javax.swing.JTextArea();
        checkSitemap = new javax.swing.JCheckBox();
        crearCategoria = new javax.swing.JButton();
        salirCrear = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        panelPrincipal.setBackground(new java.awt.Color(154, 218, 237));
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelCrearCategoria.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelCrearCategoria.setText("CREAR CATEGORÍA");
        panelPrincipal.add(labelCrearCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        imgEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/principal.png"))); // NOI18N
        panelPrincipal.add(imgEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, -1, 450));

        labelNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelNombre.setText("Nombre");
        panelPrincipal.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        labelTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTitulo.setText("Título");
        panelPrincipal.add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        labelContenido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelContenido.setText("Contenido");
        panelPrincipal.add(labelContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        labelMetadescription.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelMetadescription.setText("Metadescription");
        panelPrincipal.add(labelMetadescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        labelSitemap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelSitemap.setText("Sitemap");
        panelPrincipal.add(labelSitemap, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, -1, -1));

        textNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        panelPrincipal.add(textNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 300, 30));

        textTitulo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        panelPrincipal.add(textTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 300, 30));

        textContenido.setColumns(20);
        textContenido.setLineWrap(true);
        textContenido.setRows(5);
        textContenido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textContenidoKeyPressed(evt);
            }
        });
        scrollContenido.setViewportView(textContenido);

        panelPrincipal.add(scrollContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 300, 150));

        textMetadesc.setColumns(20);
        textMetadesc.setLineWrap(true);
        textMetadesc.setRows(5);
        textMetadesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textMetadescKeyPressed(evt);
            }
        });
        scrollMetadesc.setViewportView(textMetadesc);

        panelPrincipal.add(scrollMetadesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 300, 100));

        checkSitemap.setText("Check si quieres que se indexe la categoría");
        checkSitemap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                checkSitemapKeyPressed(evt);
            }
        });
        panelPrincipal.add(checkSitemap, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, -1, 20));

        crearCategoria.setText("CREAR CATEGORIA");
        crearCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCategoriaActionPerformed(evt);
            }
        });
        panelPrincipal.add(crearCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, 170, 40));

        salirCrear.setText("SALIR");
        salirCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirCrearActionPerformed(evt);
            }
        });
        panelPrincipal.add(salirCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     * @param evt
     *
     * AÑADIMOS LOS EVENTOS NECESARIOS
     */
    private void crearCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCategoriaActionPerformed
        crearCategoria();
    }//GEN-LAST:event_crearCategoriaActionPerformed

    private void salirCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirCrearActionPerformed

        this.setVisible(false);
        new menuCategorias().setVisible(true);
    }//GEN-LAST:event_salirCrearActionPerformed
    /**
     * ESTABLECEMOS VARIAS FUNCIONALIDADES PARA QUE SE PUEDA ATAJAR CON TECLADO
     *
     * @param evt
     */
    private void textContenidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textContenidoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            textMetadesc.requestFocus();
        }
    }//GEN-LAST:event_textContenidoKeyPressed

    private void textMetadescKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textMetadescKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            checkSitemap.requestFocus();
        }
    }//GEN-LAST:event_textMetadescKeyPressed

    private void checkSitemapKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_checkSitemapKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            crearCategoria.requestFocus();
        }
    }//GEN-LAST:event_checkSitemapKeyPressed

    /**
     * MODIFICAMOS LA FUNCIÓN DE CERRAR VENTANA PARA QUE EN VEZ DE SALIR DEL
     * SISTEMA, VUELVA AL PANEL DE LAS CATEGORÍAS, ACTUALIZANDO A SU PASO LA
     * LISTA CON LA NUEVA QUE SE HAYA PODIDO IMPLEMENTAR
     */
    public void funcionCerrar() {
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                new menuCategorias().setVisible(true);
            }
        });
    }

    /**
     * AÑADE NUESTRA CATEGORÍA, RECOGIENDO LOS VALORES NECESARIOS
     */
    private void crearCategoria() {

        bbdd conexion = new bbdd();
        String nombre = textNombre.getText();
        String title = textTitulo.getText();
        String cont = textContenido.getText();
        String meta = textMetadesc.getText();
        boolean check = checkSitemap.isSelected();
        int checked;
        checked = (check) ? 1 : 0;
        LocalDateTime ldt = LocalDateTime.now();
        String date = DateTimeFormatter.ofPattern("yyyy-MM-dd").format(ldt);

        /**
         * SI EL NOMBRE EXISTE EN LA BBDD MUESTRA ERROR, SEÑALA EL FONDO EN ROJO
         * Y VUELVE A CAMBIARLO CUANDO CAMBIE EL CONTENIDO
         */
        if (conexion.checkNombreCategoria(nombre)) {
            /**
             * SI LA METADESCRIPCIÓN O EL TÍTULO NO TIENE LA LONGITUD DEFINIDA
             * MUESTRA ERROR, EN EL CASO DEL TÍTULO PONEMOS LA MISMA FUNCIÓN DE
             * ROJO HASTA QUE CAMBIA EL TEXTO
             */
            if (meta.length() > 56) {
                if (title.length() > 5) {
                    Categoria cat = new Categoria(nombre, title, cont, meta, checked, date);
                    conexion.crearCategoria(cat);
                    this.setVisible(false);
                    new menuCategorias().setVisible(true);
                } else {
                    textTitulo.setBackground(Color.red);
                    textTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
                        @Override
                        public void keyPressed(java.awt.event.KeyEvent evt) {
                            fieldNameKeyPressed(evt);
                        }

                        private void fieldNameKeyPressed(KeyEvent evt) {
                            if (textTitulo.hasFocus()) {
                                textTitulo.setBackground(Color.white);
                            } //To change body of generated methods, choose Tools | Templates.
                        }
                    });
                    JOptionPane.showMessageDialog(null, "El título es demasiado pequeño. Debe tener mínimo 10 caracteres",
                            "Revisa la metadescription", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "El contenido de la metadescripcion es demasiado pequeño. Debe tener mínimo 56 caracteres",
                        "Revisa la metadescription", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            /**
             * SI HAY OTRA CATEGORÍA NOMBRADA IGUAL, HACEMOS QUE SE PONGA EN
             * ROJO EL NOMBRE PARA AVISAR AL USUARIO DEL ERROR, QUE DESAPARECERÁ
             * CUANDO VUELVA A INSERTAR O QUITAR CUALQUIER CARÁCTER
             */
            textNombre.setBackground(Color.red);
            textNombre.addKeyListener(new java.awt.event.KeyAdapter() {
                @Override
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    fieldNameKeyPressed(evt);
                }

                private void fieldNameKeyPressed(KeyEvent evt) {
                    if (textNombre.hasFocus()) {
                        textNombre.setBackground(Color.white);
                    } //To change body of generated methods, choose Tools | Templates.
                }
            });
            JOptionPane.showMessageDialog(null, "Ese nombre de categoría ya existe",
                    "Error al crear", JOptionPane.ERROR_MESSAGE);
        }
        conexion.close();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkSitemap;
    private javax.swing.JButton crearCategoria;
    private javax.swing.JLabel imgEmpresa;
    private javax.swing.JLabel labelContenido;
    private javax.swing.JLabel labelCrearCategoria;
    private javax.swing.JLabel labelMetadescription;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelSitemap;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JButton salirCrear;
    private javax.swing.JScrollPane scrollContenido;
    private javax.swing.JScrollPane scrollMetadesc;
    private javax.swing.JTextArea textContenido;
    private javax.swing.JTextArea textMetadesc;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textTitulo;
    // End of variables declaration//GEN-END:variables
}
