/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProyectoSprint3;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author amore
 */
public class GUICrearUsuario extends javax.swing.JFrame {

    /**
     * Creates new form GUICrearUsuario
     */
    public GUICrearUsuario() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getClassLoader().getResource("imagenes/icon.jpg")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        crearusuLabel = new javax.swing.JLabel();
        imgEmpresa = new javax.swing.JLabel();
        labelNom = new javax.swing.JLabel();
        fieldName = new javax.swing.JTextField();
        labelPass = new javax.swing.JLabel();
        fieldPass = new javax.swing.JPasswordField();
        labelPassCheck = new javax.swing.JLabel();
        fieldPassCheck = new javax.swing.JPasswordField();
        ejecutarRegistro = new javax.swing.JLabel();
        volverLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(154, 218, 237));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crearusuLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        crearusuLabel.setText("CREA TU NUEVO USUARIO");
        jPanel2.add(crearusuLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 250, 60));

        imgEmpresa.setBackground(new java.awt.Color(154, 218, 237));
        imgEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/principal.png"))); // NOI18N
        jPanel2.add(imgEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 290, 450));

        labelNom.setText("NOMBRE");
        jPanel2.add(labelNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 100, 40));

        fieldName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldNameKeyPressed(evt);
            }
        });
        jPanel2.add(fieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 120, 40));

        labelPass.setText("PASSWORD");
        jPanel2.add(labelPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 100, 40));

        fieldPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldPassKeyPressed(evt);
            }
        });
        jPanel2.add(fieldPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 120, 40));

        labelPassCheck.setText("REPITA LA PASSWORD");
        jPanel2.add(labelPassCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 150, 40));

        fieldPassCheck.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldPassCheckKeyPressed(evt);
            }
        });
        jPanel2.add(fieldPassCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 120, 40));

        ejecutarRegistro.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        ejecutarRegistro.setText("Registrar");
        ejecutarRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ejecutarRegistroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ejecutarRegistroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ejecutarRegistroMouseExited(evt);
            }
        });
        ejecutarRegistro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ejecutarRegistroKeyPressed(evt);
            }
        });
        jPanel2.add(ejecutarRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 80, 30));

        volverLogin.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        volverLogin.setText("Vuelve a Login");
        volverLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                volverLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                volverLoginMouseExited(evt);
            }
        });
        jPanel2.add(volverLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldNameKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            fieldPass.requestFocus();
        }
    }//GEN-LAST:event_fieldNameKeyPressed

    private void fieldPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldPassKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            fieldPassCheck.requestFocus();
        }
    }//GEN-LAST:event_fieldPassKeyPressed

    private void fieldPassCheckKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldPassCheckKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            createUser();
        }
    }//GEN-LAST:event_fieldPassCheckKeyPressed

    private void ejecutarRegistroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ejecutarRegistroKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            createUser();
        }
    }//GEN-LAST:event_ejecutarRegistroKeyPressed

    private void ejecutarRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ejecutarRegistroMouseClicked
        createUser();
    }//GEN-LAST:event_ejecutarRegistroMouseClicked

    private void volverLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverLoginMouseClicked
        this.setVisible(false);
        new GUILog().setVisible(true);
    }//GEN-LAST:event_volverLoginMouseClicked

    private void ejecutarRegistroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ejecutarRegistroMouseEntered
        ejecutarRegistro.setForeground(Color.red);
    }//GEN-LAST:event_ejecutarRegistroMouseEntered

    private void ejecutarRegistroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ejecutarRegistroMouseExited
        ejecutarRegistro.setForeground(Color.black);
    }//GEN-LAST:event_ejecutarRegistroMouseExited

    private void volverLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverLoginMouseEntered
        volverLogin.setForeground(Color.red);
    }//GEN-LAST:event_volverLoginMouseEntered

    private void volverLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverLoginMouseExited
        volverLogin.setForeground(Color.black);
    }//GEN-LAST:event_volverLoginMouseExited

    /**
     * @param args the command line arguments
     */
    private void createUser() {

        try {
            bbdd conexion = new bbdd();
            String user = fieldName.getText();
            String pass = new String(fieldPass.getPassword());
            String passCheck = new String(fieldPassCheck.getPassword());

            if (pass.length() < 3 || user.length() < 3) {
                JOptionPane.showMessageDialog(null, "El usuario "
                        + "o contraseña tiene que tener más de 2 caracteres\n",
                        "Error", JOptionPane.WARNING_MESSAGE);
                fieldName.requestFocus();
                fieldPass.setText("");
                fieldPassCheck.setText("");
            } else {
                if (pass.equals(passCheck)) {
                    byte check = conexion.datosCreate(user);
                    if (check >= 1) {
                        JOptionPane.showMessageDialog(null, "Este usuario ya "
                                + "está siendo usado\n",
                                "Error", JOptionPane.WARNING_MESSAGE);
                        fieldName.setText("");
                        fieldPass.setText("");
                        fieldPassCheck.setText("");
                        fieldName.requestFocus();
                    } else if (check == 0) {
                        conexion.crearUsuario(user, pass);
                        JOptionPane.showMessageDialog(null, "El usuario "
                                + " ha sido creado. Te redirigimos a la "
                                + "pantalla de login:\n",
                                "Registro satisfactorio",
                                JOptionPane.INFORMATION_MESSAGE);
                        this.setVisible(false);
                        new GUILog().setVisible(true);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Las contraseñas "
                            + "introducidas son diferentes:\n",
                            "Error", JOptionPane.ERROR_MESSAGE);
                    fieldPass.setText("");
                    fieldPassCheck.setText("");
                    fieldPass.requestFocus();
                }
            }
            conexion.close();
        } catch (Exception e) {
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel crearusuLabel;
    private javax.swing.JLabel ejecutarRegistro;
    private javax.swing.JTextField fieldName;
    private javax.swing.JPasswordField fieldPass;
    private javax.swing.JPasswordField fieldPassCheck;
    private javax.swing.JLabel imgEmpresa;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelNom;
    private javax.swing.JLabel labelPass;
    private javax.swing.JLabel labelPassCheck;
    private javax.swing.JLabel volverLogin;
    // End of variables declaration//GEN-END:variables
}
