/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProyectoSprint3;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.PrintStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author amore
 */
public class GUILog extends javax.swing.JFrame {

    /**
     * Creates new form GUILog
     */
    private int i = 0;

    public GUILog() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getClassLoader().getResource("imagenes/icon.jpg")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        labGestion = new javax.swing.JLabel();
        imgEmpresa = new javax.swing.JLabel();
        labelNom = new javax.swing.JLabel();
        fieldName = new javax.swing.JTextField();
        labelPass = new javax.swing.JLabel();
        fieldPass = new javax.swing.JPasswordField();
        createUser = new javax.swing.JLabel();
        logUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(154, 218, 237));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labGestion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labGestion.setText("Bievenido a Gestion de Categorías");
        jPanel2.add(labGestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        imgEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/principal.png"))); // NOI18N
        jPanel2.add(imgEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 290, 450));

        labelNom.setText("NOMBRE");
        jPanel2.add(labelNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 100, 40));

        fieldName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldNameKeyPressed(evt);
            }
        });
        jPanel2.add(fieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 120, 40));

        labelPass.setText("PASSWORD");
        jPanel2.add(labelPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 100, 40));

        fieldPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldPassKeyPressed(evt);
            }
        });
        jPanel2.add(fieldPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 120, 40));

        createUser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        createUser.setText("CREAR USUARIO");
        createUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                createUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                createUserMouseExited(evt);
            }
        });
        jPanel2.add(createUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 180, 50));

        logUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        logUser.setText("ENTRAR");
        logUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logUserMouseExited(evt);
            }
        });
        jPanel2.add(logUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 120, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createUserMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new GUICrearUsuario().setVisible(true);

    }//GEN-LAST:event_createUserMouseClicked

    private void fieldNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldNameKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            fieldPass.requestFocus();
        }
    }//GEN-LAST:event_fieldNameKeyPressed

    private void fieldPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldPassKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            loginUser();
        }
    }//GEN-LAST:event_fieldPassKeyPressed

    private void logUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logUserMouseClicked
        loginUser();
    }//GEN-LAST:event_logUserMouseClicked

    private void logUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logUserMouseEntered
        logUser.setForeground(Color.red);
    }//GEN-LAST:event_logUserMouseEntered

    private void logUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logUserMouseExited
        logUser.setForeground(Color.black);
    }//GEN-LAST:event_logUserMouseExited

    private void createUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createUserMouseEntered
        createUser.setForeground(Color.red);
    }//GEN-LAST:event_createUserMouseEntered

    private void createUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createUserMouseExited
        createUser.setForeground(Color.black);
    }//GEN-LAST:event_createUserMouseExited

    private void loginUser() {
        try {
            bbdd conexion = new bbdd();
            String pass = new String(fieldPass.getPassword());
            String user = fieldName.getText();
            if (conexion.datosUsuario(user, pass) == 1) {
                this.setVisible(false);
                new menuCategorias().setVisible(true);
            } else {
                if (conexion.datosUsuario(user, pass) == 0) {
                    JOptionPane.showMessageDialog(null, "No existe el usuario introducido.", "", JOptionPane.WARNING_MESSAGE);
                }
                i++;
                fieldName.requestFocus();
                fieldName.setText("");
                fieldPass.setText("");
                if (i == 3) {
                    JOptionPane.showMessageDialog(null, "Has introducido mal la contraseña o el usuario 3 veces. \n El sistema se desconectará", "", JOptionPane.WARNING_MESSAGE);
                    System.exit(0);
                }
            }
            conexion.close();
        } catch (HeadlessException e) {
            PrintStream s = null;
            e.printStackTrace(s);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel createUser;
    private javax.swing.JTextField fieldName;
    private javax.swing.JPasswordField fieldPass;
    private javax.swing.JLabel imgEmpresa;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labGestion;
    private javax.swing.JLabel labelNom;
    private javax.swing.JLabel labelPass;
    private javax.swing.JLabel logUser;
    // End of variables declaration//GEN-END:variables
}
